// <auto-generated />
using System;
using ES2_webapp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ES2_webapp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250522161153_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CargoUtilizador", b =>
                {
                    b.Property<decimal>("CargosIdCargo")
                        .HasColumnType("numeric");

                    b.Property<decimal>("UtilizadoresIdUtilizador")
                        .HasColumnType("numeric");

                    b.HasKey("CargosIdCargo", "UtilizadoresIdUtilizador");

                    b.HasIndex("UtilizadoresIdUtilizador");

                    b.ToTable("CargoUtilizador");
                });

            modelBuilder.Entity("Membro", b =>
                {
                    b.Property<decimal>("IdMembro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric");

                    b.Property<decimal>("IdProjeto")
                        .HasColumnType("numeric");

                    b.Property<decimal>("IdProjetoNavigationIdProjeto")
                        .HasColumnType("numeric");

                    b.Property<decimal>("IdUtilizador")
                        .HasColumnType("numeric");

                    b.Property<decimal>("IdUtilizadorNavigationIdUtilizador")
                        .HasColumnType("numeric");

                    b.Property<decimal>("NHabitualHoras")
                        .HasColumnType("numeric");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdMembro");

                    b.HasIndex("IdProjetoNavigationIdProjeto");

                    b.HasIndex("IdUtilizadorNavigationIdUtilizador");

                    b.ToTable("Membros");
                });

            modelBuilder.Entity("ProjetoTarefa", b =>
                {
                    b.Property<decimal>("ProjetoId")
                        .HasColumnType("numeric");

                    b.Property<int>("TarefaId")
                        .HasColumnType("integer");

                    b.HasKey("ProjetoId", "TarefaId");

                    b.HasIndex("TarefaId");

                    b.ToTable("ProjetoTarefa");
                });

            modelBuilder.Entity("Tarefa", b =>
                {
                    b.Property<int>("IdTarefa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTarefa"));

                    b.Property<DateOnly?>("DtFim")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DtInicio")
                        .HasColumnType("date");

                    b.Property<TimeSpan>("HrFim")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("HrInicio")
                        .HasColumnType("interval");

                    b.Property<decimal>("IdProjeto")
                        .HasColumnType("numeric");

                    b.Property<string>("NomeTarefa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("PrecoHora")
                        .HasColumnType("numeric");

                    b.HasKey("IdTarefa");

                    b.HasIndex("IdProjeto");

                    b.ToTable("Tarefas");
                });

            modelBuilder.Entity("WebApplication2.Entities.Projeto", b =>
                {
                    b.Property<decimal>("IdProjeto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric");

                    b.Property<decimal>("IdUtilizador")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("IdUtilizadorNavigationIdUtilizador")
                        .HasColumnType("numeric");

                    b.Property<string>("NomeCliente")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomeProjeto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdProjeto");

                    b.HasIndex("IdUtilizadorNavigationIdUtilizador");

                    b.ToTable("Projetos");
                });

            modelBuilder.Entity("WebApplication2.Entities.Utilizador", b =>
                {
                    b.Property<decimal>("IdUtilizador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric");

                    b.Property<decimal?>("NHabitualHoras")
                        .HasColumnType("numeric");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdUtilizador");

                    b.ToTable("Utilizadores");
                });

            modelBuilder.Entity("WebApplication2.Models.Cargo", b =>
                {
                    b.Property<decimal>("IdCargo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdCargo");

                    b.ToTable("Cargos");
                });

            modelBuilder.Entity("WebApplication2.Models.Convites", b =>
                {
                    b.Property<decimal>("IdMensagem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric");

                    b.Property<decimal>("IdUtilizador")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("IdUtilizadorNavigationIdUtilizador")
                        .HasColumnType("numeric");

                    b.Property<decimal>("IdUtilizadorRemetente")
                        .HasColumnType("numeric");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Resposta")
                        .HasColumnType("boolean");

                    b.HasKey("IdMensagem");

                    b.HasIndex("IdUtilizadorNavigationIdUtilizador");

                    b.ToTable("Convites");
                });

            modelBuilder.Entity("WebApplication2.Models.Equipas", b =>
                {
                    b.Property<decimal>("idEquipa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric");

                    b.Property<decimal?>("NHabitualHoras")
                        .HasColumnType("numeric");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("idEquipa");

                    b.ToTable("Equipas");
                });

            modelBuilder.Entity("CargoUtilizador", b =>
                {
                    b.HasOne("WebApplication2.Models.Cargo", null)
                        .WithMany()
                        .HasForeignKey("CargosIdCargo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication2.Entities.Utilizador", null)
                        .WithMany()
                        .HasForeignKey("UtilizadoresIdUtilizador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Membro", b =>
                {
                    b.HasOne("WebApplication2.Entities.Projeto", "IdProjetoNavigation")
                        .WithMany("Membros")
                        .HasForeignKey("IdProjetoNavigationIdProjeto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication2.Entities.Utilizador", "IdUtilizadorNavigation")
                        .WithMany("Membros")
                        .HasForeignKey("IdUtilizadorNavigationIdUtilizador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdProjetoNavigation");

                    b.Navigation("IdUtilizadorNavigation");
                });

            modelBuilder.Entity("ProjetoTarefa", b =>
                {
                    b.HasOne("WebApplication2.Entities.Projeto", "Projeto")
                        .WithMany("ProjetosTarefas")
                        .HasForeignKey("ProjetoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tarefa", "Tarefa")
                        .WithMany("ProjetosTarefas")
                        .HasForeignKey("TarefaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Projeto");

                    b.Navigation("Tarefa");
                });

            modelBuilder.Entity("Tarefa", b =>
                {
                    b.HasOne("WebApplication2.Entities.Projeto", "Projeto")
                        .WithMany()
                        .HasForeignKey("IdProjeto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Projeto");
                });

            modelBuilder.Entity("WebApplication2.Entities.Projeto", b =>
                {
                    b.HasOne("WebApplication2.Entities.Utilizador", "IdUtilizadorNavigation")
                        .WithMany()
                        .HasForeignKey("IdUtilizadorNavigationIdUtilizador");

                    b.Navigation("IdUtilizadorNavigation");
                });

            modelBuilder.Entity("WebApplication2.Models.Convites", b =>
                {
                    b.HasOne("WebApplication2.Entities.Utilizador", "IdUtilizadorNavigation")
                        .WithMany()
                        .HasForeignKey("IdUtilizadorNavigationIdUtilizador");

                    b.Navigation("IdUtilizadorNavigation");
                });

            modelBuilder.Entity("Tarefa", b =>
                {
                    b.Navigation("ProjetosTarefas");
                });

            modelBuilder.Entity("WebApplication2.Entities.Projeto", b =>
                {
                    b.Navigation("Membros");

                    b.Navigation("ProjetosTarefas");
                });

            modelBuilder.Entity("WebApplication2.Entities.Utilizador", b =>
                {
                    b.Navigation("Membros");
                });
#pragma warning restore 612, 618
        }
    }
}
